[build]
publish = "public"
command = "bundle && npm run production && hugo --gc --minify -b hhttps://eclipsefdn-asciidoc-wg.netlify.app --destination public"

[build.environment]
NODE_VERSION = "14.16.0"

[context.production.environment]
HUGO_VERSION = "0.76.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run production && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.76.5"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run production && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --destination public"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76.5"

[context.branch-deploy]
command = "npm run production && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
